_target_: transformers.TrainingArguments

# macro
run_name: ${name}
num_train_epochs: 3
per_device_train_batch_size: 4
per_device_eval_batch_size: 32

# lr
learning_rate: 3e-5
lr_scheduler_type: cosine
warmup_steps: 2

# precision
fp16: false
bf16: false

# eval
# eval_strategy: epoch
# eval_steps: 100  # not used if eval_strategy is epoch

# checkpoints
save_strategy: epoch
save_steps: 100  # not used if save_strategy is epoch

# logging & callbacks
logging_strategy: steps
logging_first_step: true
logging_steps: 2

# accelerate
dataloader_drop_last: true
# fsdp: ["full_shard", "auto_wrap"]
# fsdp_config: ${accelerate.fsdp_config}


seed: 123
